#INITIAL SETTINGS
data_name: data.csv
drop_columns: ["id","Unnamed: 32"]
target_name: class
test_size: 0.3
model_directory: ./
model_name: KNN_classifier.pkl


#kNN parameters
n_neighbors: 6
weights: uniform
algorithm: auto
leaf_size: 20
p: 2
metric: minkowski
n_jobs: 1